service: omni-fourkites-spacex-air

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  stackTags:
    Application: Omni fourkites spacex air
    CreateBy: BizCloudExperts
    Environment: ${self:provider.stage}

package:
  individually: true
  exclude:
    - "node_modules/**"
    - Jenkinsfile
    - "config/**"
    - "src/**"
    - "*.*"

layers:
  OmnifourkitesLayer:
    path: lib
    compatibleRuntimes:
      - nodejs18.x
    name: omni-fourkites-layer-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-aws-alias-fixed
  
functions:
  fourkitesCwAir: ${file(config/functions/airCw.yml):function}

resources:
  Resources:
    SpacexAirLogTable: ${file(config/dynamoDB/spacexLogTable.yml):SpacexAirLogTable}