SpacexAirLogTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: spacex-air-logs-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "ShipmentId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "ShipmentId"
        KeyType: "HASH"