---
function:
  name: omni-fourkites-spacex-air-${self:provider.stage}
  handler: src/AirCw/index.handler
  timeout: 120
  runtime: nodejs16.x
  layers:
    - { Ref: OmnifourkitesLayerLambdaLayer }

  package:
    include:
      - src/AirCw/index.js
      - src/shared/**
  events:
    - existingS3:
        bucket: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
        events: 
          - s3:ObjectCreated:*
        rules:
          - prefix: ${ssm:/omni-dw-fourkites/${self:provider.stage}/spacex-air/s3-prefix} #check for prod value
          - suffix: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/rules/suffix}

  environment:
    BUCKET: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
    ERROR_SNS_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    SPACEX_AIR_ENDPOINT: ${ssm:/omni-fourkites/${self:provider.stage}/spacex-air/api/endpoint~true}
    SPACEX_AIR_APIKEY: ${ssm:/omni-fourkites/${self:provider.stage}/spacex-air/api/key~true}
    FUNCTION_NAME: omni-fourkites-spacex-air-${self:provider.stage}
    SPACEX_AIR_LOGS_TABLE: ${ssm:/omni-fourkites/${self:provider.stage}/spacex-logs/ddb.tableName}
    EADAPTER_URL: ${ssm:/omni-dw/${self:provider.stage}/wms/adapter/url}
    EADAPTER_USERNAME: ${ssm:/omni-dw/${self:provider.stage}/wms/adapter/password}
    EADAPTER_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/wms/adapter/username}       