function:
  name: omni-fourkites-airWt-${self:provider.stage}
  handler: src/AirWt/index.handler
  timeout: 120
  layers:
    - { Ref: OmnifourkitesLayerLambdaLayer }
  environment:
    BUCKET: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
  package:
    include:
      - src/AirWt/**
      - src/shared/**
  # events:
  #   - s3:
  #       bucket: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
  #       event: s3:ObjectCreated:*
  #       rules:
  #         - prefix: Test/test_air_cw.xml
  #         - suffix: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/rules/suffix}
  #       existing: true